import {
  FaBehance,
  FaDev,
  FaDiscord,
  FaDribbble,
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaLinkedin,
  FaMedium,
  FaPatreon,
  FaPinterest,
  FaReddit,
  FaSlack,
  FaSnapchatGhost,
  FaSoundcloud,
  FaSpotify,
  FaTelegram,
  FaTiktok,
  FaTumblr,
  FaTwitch,
  FaVimeoV,
  FaWhatsapp,
  FaYoutube,
} from 'react-icons/fa'
import { FaGoogle, FaMastodon, FaThreads, FaXTwitter } from 'react-icons/fa6'
import { SiCodepen, SiGumroad, SiLinktree, SiNotion, SiSubstack } from 'react-icons/si'
import { TbWorld } from 'react-icons/tb'

export const PLATFORMS = [
  {
    icon: <FaXTwitter className='size-4' />,
    id: 'twitter',
    name: 'Twitter/X',
    prefix: 'https://twitter.com/',
  },
  {
    icon: <FaInstagram className='size-4' />,
    id: 'instagram',
    name: 'Instagram',
    prefix: 'https://instagram.com/',
  },
  {
    icon: <FaFacebook className='size-4' />,
    id: 'facebook',
    name: 'Facebook',
    prefix: 'https://facebook.com/',
  },
  {
    icon: <FaLinkedin className='size-4' />,
    id: 'linkedin',
    name: 'LinkedIn',
    prefix: 'https://linkedin.com/in/',
  },
  {
    icon: <FaGithub className='size-4' />,
    id: 'github',
    name: 'GitHub',
    prefix: 'https://github.com/',
  },
  {
    icon: <FaYoutube className='size-4' />,
    id: 'youtube',
    name: 'YouTube',
    prefix: 'https://youtube.com/',
  },
  {
    icon: <FaTiktok className='size-4' />,
    id: 'tiktok',
    name: 'TikTok',
    prefix: 'https://tiktok.com/@',
  },
  {
    icon: <FaThreads className='size-4' />,
    id: 'threads',
    name: 'Threads',
    prefix: 'https://threads.net/@',
  },
  {
    icon: <FaReddit className='size-4' />,
    id: 'reddit',
    name: 'Reddit',
    prefix: 'https://reddit.com/user/',
  },
  {
    icon: <FaPinterest className='size-4' />,
    id: 'pinterest',
    name: 'Pinterest',
    prefix: 'https://pinterest.com/',
  },
  {
    icon: <FaTwitch className='size-4' />,
    id: 'twitch',
    name: 'Twitch',
    prefix: 'https://twitch.tv/',
  },
  {
    icon: <FaDiscord className='size-4' />,
    id: 'discord',
    name: 'Discord',
    prefix: 'https://discord.gg/',
  },
  {
    icon: <FaSlack className='size-4' />,
    id: 'slack',
    name: 'Slack',
    prefix: 'https://slack.com/',
  },
  {
    icon: <FaSnapchatGhost className='size-4' />,
    id: 'snapchat',
    name: 'Snapchat',
    prefix: 'https://snapchat.com/add/',
  },
  {
    icon: <FaWhatsapp className='size-4' />,
    id: 'whatsapp',
    name: 'WhatsApp',
    prefix: 'https://wa.me/',
  },
  {
    icon: <FaTelegram className='size-4' />,
    id: 'telegram',
    name: 'Telegram',
    prefix: 'https://t.me/',
  },
  {
    icon: <FaMedium className='size-4' />,
    id: 'medium',
    name: 'Medium',
    prefix: 'https://medium.com/@',
  },
  {
    icon: <SiSubstack className='size-4' />,
    id: 'substack',
    name: 'Substack',
    prefix: 'https://substack.com/@',
  },
  {
    icon: <FaDev className='size-4' />,
    id: 'dev',
    name: 'Dev.to',
    prefix: 'https://dev.to/',
  },
  {
    icon: <FaBehance className='size-4' />,
    id: 'behance',
    name: 'Behance',
    prefix: 'https://behance.net/',
  },
  {
    icon: <FaDribbble className='size-4' />,
    id: 'dribbble',
    name: 'Dribbble',
    prefix: 'https://dribbble.com/',
  },
  {
    icon: <FaVimeoV className='size-4' />,
    id: 'vimeo',
    name: 'Vimeo',
    prefix: 'https://vimeo.com/',
  },
  {
    icon: <FaSoundcloud className='size-4' />,
    id: 'soundcloud',
    name: 'SoundCloud',
    prefix: 'https://soundcloud.com/',
  },
  {
    icon: <FaSpotify className='size-4' />,
    id: 'spotify',
    name: 'Spotify',
    prefix: 'https://open.spotify.com/user/',
  },
  {
    icon: <FaMastodon className='size-4' />,
    id: 'mastodon',
    name: 'Mastodon',
    prefix: 'https://',
  },
  {
    icon: <FaTumblr className='size-4' />,
    id: 'tumblr',
    name: 'Tumblr',
    prefix: 'https://',
  },
  {
    icon: <FaPatreon className='size-4' />,
    id: 'patreon',
    name: 'Patreon',
    prefix: 'https://patreon.com/',
  },
  {
    icon: <SiGumroad className='size-4' />,
    id: 'gumroad',
    name: 'Gumroad',
    prefix: 'https://gumroad.com/',
  },
  {
    icon: <SiCodepen className='size-4' />,
    id: 'codepen',
    name: 'CodePen',
    prefix: 'https://codepen.io/',
  },
  {
    icon: <SiLinktree className='size-4' />,
    id: 'linktree',
    name: 'Linktree',
    prefix: 'https://linktr.ee/',
  },
  {
    icon: <SiNotion className='size-4' />,
    id: 'notion',
    name: 'Notion',
    prefix: 'https://notion.site/',
  },
  {
    icon: <FaGoogle className='size-4' />,
    id: 'google',
    name: 'Google',
    prefix: 'https://google.com/',
  },
  {
    icon: <TbWorld className='size-4' />,
    id: 'custom',
    name: 'Otro',
    prefix: '',
  },
]
